[build]
  command = "turbo run @hrishikeshk/site#deploy"
  publish = "./packages/site/build/"

[dev]
  command = "turbo run @hrishikeshk/site#dev"
  targetPort = 5173

[[headers]]
  for = "/*"
  [headers.values]
    x-robots-tag = "noindex"